---
title: "gcrc_baseline_chara"
author: "Study authors"
date: "`r Sys.Date()`"
output: html_document
---


### **加载R包**

```{r include=FALSE,collapse=TRUE}
library(plyr)
library(dplyr) # mutate
library(tidyr) # %>% 
library(tableone)
```



### **读取数据**

```{r include=FALSE,collapse=TRUE}
gcrc_data <- readRDS("./output_data/gcrc/data_analyze_gcrc.rds")

data <- gcrc_data # 分析数据data1
```

#### *查看数据*

```{r collapse=TRUE}
dput(names(data))
str(data)

skimr::skim(data)
```



### **描述性统计**

```{r collapse=TRUE}
covars <-c("time", "Age", "Age_group", "Age_clas", "Sex", "Smoking", "Drinking", "History",
           "PGI", "PGI_gc","PGI_crc", "PGI_gcrc", "PGII", "PGII_gcrc")

fvars<-c( "Age_group", "Age_clas", "Sex", "Smoking", "Drinking", "History",
          "PGI_gc","PGI_crc", "PGI_gcrc", "PGII_gcrc")
```


#### *胃癌*

```{r collapse=TRUE}
# 胃癌
chara1 <- CreateTableOne(vars = covars,
                         data =data,
                         strata = "Stomach",
                         factorVars = fvars)
chara1

chara1_table <- print(chara1,
                      nonnormal = c("time", "Age", "PGI", "PGII", "PGR", "G17"),
                      showAllLevels=TRUE,
                      formatOptions = list(big.mark = ","))

# 肠癌
chara2 <- CreateTableOne(vars = covars,
                         strata = "Colorectal",
                         data =data,
                         factorVars = fvars)
chara2

chara2_table <- print(chara2,
                      nonnormal = c("time", "Age", "PGI", "PGII", "PGR", "G17"),
                      showAllLevels=TRUE,
                      formatOptions = list(big.mark = ",")) 

# 胃肠癌
chara3 <- CreateTableOne(vars = covars,
                         strata = "gcrc",
                         data =data,
                         factorVars = fvars)
chara3

chara3_table <- print(chara3,
                      nonnormal = c("time", "Age", "PGI", "PGII", "PGR", "G17"),
                      showAllLevels=TRUE,
                      formatOptions = list(big.mark = ",")) 


chara_table <- cbind(chara1_table, chara2_table, chara3_table)
chara_df <- as.data.frame(chara_table)

write.csv(chara_df, file = "./output_table/5. gcrc/0. baseline/gcrc_baseline_chara.csv")
```

